# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-24151b73-5cda-4b95-a5b4-0be6cfc4fb42";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-24151b73-5cda-4b95-a5b4-0be6cfc4fb42".device = "/dev/disk/by-uuid/24151b73-5cda-4b95-a5b4-0be6cfc4fb42";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/1228-9212";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-f9c32740-0c68-4913-9a0f-d26df56b3aa1";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
