# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/luks-767d4c3e-fdac-4a4e-a24a-c7da86dc502d";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-767d4c3e-fdac-4a4e-a24a-c7da86dc502d".device = "/dev/disk/by-uuid/767d4c3e-fdac-4a4e-a24a-c7da86dc502d";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/0D9B-BC0A";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [
    {device = "/dev/mapper/luks-e795a919-6fdc-42e4-b35d-1ed2eb10e962";}
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
